# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate pyseamsdev
#
name: pyseamsdev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - pkg-config
  - clang
  # d-SEAMS deps
  - yaml-cpp
  - boost-cpp
  - fmt==9.1.0
  - eigen==3.4.0
  # Python
  - pdm
<<<<<<< HEAD
<<<<<<< HEAD
  - pybind11
=======
  - fmt=="9.1.0"
>>>>>>> 3167f69 (ENH: added fmt as a dependency)
=======
  - "fmt==9.1.0"
>>>>>>> 1b36832 (ENH: once more)
